### ISSUE TITLE
[bug] WatchOS system problem

### ISSUE THREAD

**Issue by paulo-coutinho** [leetal/ios-cmake#107] opened 2021-03-31 16:21 UTC
Hi,

When i build for watchos and cmake 3.20 i get:

```
CMake Error at CMakeLists.txt:214 (add_library):
  Attempting to use @rpath without CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG being
  set.  This could be because you are using a Mac OS X version less than 10.5
  or because CMake's platform configuration is corrupt.


CMake Error at CMakeLists.txt:214 (add_library):
  Attempting to use @rpath without CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG being
  set.  This could be because you are using a Mac OS X version less than 10.5
  or because CMake's platform configuration is corrupt.
```

Do you know what can be wrong?

**Comment by leetal** [comment] 2021-03-31 16:45
Do you have a small reproducer perhaps? Are the example projects also failing?

**Comment by paulo-coutinho** [comment] 2021-03-31 18:26
Im using in my own project called ezored (github.com/ezored/ezored):

```
if (PROJECT_CONFIG_GROUP STREQUAL "ios" OR "ios_simulator")
    set(DEVICE_FAMILY "1,2" CACHE STRING "Device Family")
elseif (PROJECT_CONFIG_GROUP STREQUAL "tvos" OR "tvos_simulator")
    set(DEVICE_FAMILY "3" CACHE STRING "Device Family")
elseif (PROJECT_CONFIG_GROUP STREQUAL "watchos")
    set(DEVICE_FAMILY "4" CACHE STRING "Device Family")
    set(CMAKE_SYSTEM_VERSION "10.5")
elseif (PROJECT_CONFIG_GROUP STREQUAL "watchos_simulator")
    set(DEVICE_FAMILY "4" CACHE STRING "Device Family")
    set(CMAKE_SYSTEM_VERSION "10.5")
endif()
```

https://github.com/ezored/ezored/blob/master/files/targets/ios_framework/cmake/CMakeLists.txt#L23-L33

I don't know why only on watchos i need set it. Do you know why?

**Comment by leetal** [comment] 2021-04-15 08:06
The error seems to be caused by `CMAKE_SYSTEM_VERSION` not being set correctly, causing a regex parsing to 
`DARWIN_MAJOR_VERSION` and `DARWIN_MINOR_VERSION` to fail in Darwin.cmake upstream.

I believe that setting `CMAKE_SYSTEM_VERSION` to something like `12.0` (notice the ".0" part) might solve the issue, so the problem might be caused by setting `DEPLOYMENT_TARGET` in the toolchain to for example `12` instead of `12.0`.

The error is most probably caused by this line in the toolchain: https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L632

It seems that CMake is addressing this issue in 3.21.0, but can be fixed by setting the `DEPLOYMENT_TARGET`.

It's hard to give more help without a smaller reproducer.

**Comment by leetal** [comment] 2021-04-15 08:10
Another note might be that removing the `set(CMAKE_SYSTEM_VERSION "10.5")` lines from your CMakeLists.txt might also fix the issue, since those lines are overriding the one set by the toolchain.

**Comment by leetal** [comment] 2021-09-30 20:11
Did you fix this?

**Closed** 2022-01-08 06:12 UTC
Labels: bug
