### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by wanJunGe** [leetal/ios-cmake#6] opened 2018-06-05 03:01 UTC
there is an error occur when i build the google test and avs-device-sdk

I enter the command on the command line:
cmake ../googletest -DIOS_DEPLOYMENT_TARGET=10.0 -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS
or 
cmake ../avs-device-sdk -DIOS_DEPLOYMENT_TARGET=10.0 -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS -DGSTREAMER_MEDIA_PLAYER=OFF -DCURL_LIBRARY=../Build-OpenSSL-cURL/archive/libcurl-7.54.1-openssl-1.0.2l-nghttp2-1.24.0/libcurl_iOS.a -DCURL_INCLUDE_DIR=../Build-OpenSSL-cURL/curl/curl-7.55.1/include -DGTEST_LIBRARY=../googletest_build/googlemock/libgmock.a -DGTEST_MAIN_LIBRARY=../googletest_build/googlemock/libgmock_main.a -DGTEST_INCLUDE_DIR=../googletest/googletest/include/ -DPKG_CONFIG_EXECUTABLE=/usr/local/bin/pkg-config

error is:

-- Building with Xcode version: 
-- Configuring iOS build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK:  for platform: SIMULATOR64
CMake Error at ../ios-cmake/ios.toolchain.cmake:172 (message):
  Invalid CMAKE_OSX_SYSROOT: does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.3/share/cmake/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:4 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

How can I build it successfully？

**Comment by yhn0071-pping** [comment] 2018-06-05 03:07
I met this problem, too.

**Comment by gaoenjoy** [comment] 2018-06-05 03:56
solved it ？？ I had same problem too

**Comment by leetal** [comment] 2018-06-05 07:53
Hi! This error often occurrs when upgrading Xcode or the iOS toolchain to a newer version. This is due to the fact that the CMAKE_OSX_SYSROOT is cached in the build-files generated by cmake. I'll have a look at it and see if i can come up with a solution. The easiest solution for now is to clean the project and rebuild it again.

**Comment by wanJunGe** [comment] 2018-06-05 09:45
Thank you for your reply。
i used 'make clean' to clean the project，the same error occured.
Is there any other way？
the project Can't be opened with Xcode and I cloned it from the Internet。

**Comment by leetal** [comment] 2018-06-13 06:35
So it seems this error may also be caused by not having Xcode installed alltogether or if you have installed the command-line tools AFTER you installed Xcode. Please try to run the command "sudo xcode-select -s /Applications/Xcode.app/Contents/Developer" and see if that fixes the problem. I will patch the toolchain to be more specific and also to hint about possible solutions to the problem.

**Comment by 101dogs** [comment] 2018-07-26 14:36
i also has this problem, seems like a cmake upgrade issues, only build ios platform goes this error。but the logs something different like @wanJunGe  post . here is my build logs. @leetal

**Comment by 101dogs** [comment] 2018-07-26 14:37
-- Building with Xcode version: 9.4
-- Configuring iOS build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk for platform: SIMULATOR64
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Building for minimum iOS version: 8.0 (SDK version: 11.4)
-- Version flags set to: -mios-simulator-version-min=8.0
-- Disabling bitcode support.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/Users/WangJ/git/kp2pserver/build/ios/iphonesimulator/CMakeFiles/CMakeOutput.log".

**Comment by 101dogs** [comment] 2018-07-27 02:35
i add the CMAKE_FIND_ROOT_PATH_BOTH in the find NinjaFindMake.cmake works
/usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/CMakeNinjaFindMake.cmake                   
# Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
# file Copyright.txt or https://cmake.org/licensing for details.


find_program(CMAKE_MAKE_PROGRAM
  NAMES ninja-build ninja
  **CMAKE_FIND_ROOT_PATH_BOTH**
  DOC "Program used to build from build.ninja files.")
mark_as_advanced(CMAKE_MAKE_PROGRAM)

**Comment by leetal** [comment] 2018-10-11 13:18
This has been fixed in version [2.1.0](https://github.com/leetal/ios-cmake/releases/tag/2.1.0). Closing the issue 🗡

**Closed by leetal** 2018-10-11 13:18 UTC

**Comment by Prowerdev** [comment] 2019-06-20 17:31
Hi @leetal , 

I am having a similar issue:

-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- Building with Xcode version: 10.2.1
CMake Deprecation Warning at /Users/prowerdev/Development/Alexa/cross-compile/iOS/ios-cmake/ios.toolchain.cmake:149 (message):
  IOS_PLATFORM argument is DEPRECATED.  Consider using the new PLATFORM
  argument instead.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)


CMake Deprecation Warning at /Users/prowerdev/Development/Alexa/cross-compile/iOS/ios-cmake/ios.toolchain.cmake:154 (message):
  IOS_DEPLOYMENT_TARGET argument is DEPRECATED.  Consider using the new
  DEPLOYMENT_TARGET argument instead.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)


-- Targeting minimum SDK version 10.0. Dropping 32-bit support.
-- Configuring iphoneos build for platform: OS64, architecture(s): arm64
-- Using SDK:  for platform: OS64 when checking compatibility
-- Enabling bitcode support by default. ENABLE_BITCODE not provided!
-- Enabling ARC support by default. ENABLE_ARC not provided!
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
CMake Error at /Users/prowerdev/Development/Alexa/cross-compile/iOS/ios-cmake/ios.toolchain.cmake:385 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)


CMake Error at /Users/prowerdev/Development/Alexa/cross-compile/iOS/ios-cmake/ios.toolchain.cmake:386 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)


CMake Error at /Users/prowerdev/Development/Alexa/cross-compile/iOS/ios-cmake/ios.toolchain.cmake:389 (message):
  Invalid CMAKE_DEVELOPER_ROOT: does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

How can I resolve it? any guidance will be helpful.

Regards,

**Comment by Dev-Govind-Patidar** [comment] 2021-05-04 13:11
CMake Error at CMakeLists.txt:131 (setup_cocos_app_config):
  Unknown CMake command "setup_cocos_app_config".


-- Configuring incomplete, errors occurred!
See also "/Users/govindsjrmac/Documents/Workspace/Toddler/Abc123Kids_Android/ios-build/CMakeFiles/CMakeOutput.log".
