### ISSUE TITLE
OS64COMBINED doesn't work, lipo -info libexample.a, Non-fat file,architecture: arm64.

### ISSUE THREAD

**Issue by nae986** [leetal/ios-cmake#55] opened 2019-07-12 12:47 UTC

**Comment by nae986** [comment] 2019-07-12 12:54
I want get the fat lib.a. Just run your demo,set the option OS64COMBINED.I get a Non-fat file.
very looking forword your reply

**Comment by leetal** [comment] 2019-07-18 15:03
Okay, what version of CMake are you using? Might have broken if Kitware have changed some necessary arguments i recent versions.

**Comment by jonmcclung** [comment] 2019-07-19 17:21
I am experiencing the same on cmake version 3.15.0:

`$ lipo -info myframework.framework/myframework`
> Non-fat file: myframework.framework/myframework is architecture: arm64

**Comment by azymohliad** [comment] 2019-08-01 08:38
With cmake 3.14.5 and xcode 10.1 I got this error:
```clang: error: invalid arch name '-arch arm64,x86_64'```

**Comment by agirault** [comment] 2019-08-01 15:37
FYI, there is now first-class support for various OSX platforms since CMake 3.14:
- [Doc](https://cmake.org/cmake/help/v3.14/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos)
- [PR](https://gitlab.kitware.com/cmake/cmake/merge_requests/2392)

In your case, you would need to:
- set [`CMAKE_SYSTEM_NAME`](https://cmake.org/cmake/help/v3.14/variable/CMAKE_SYSTEM_NAME.html) to `iOS`
- set [`CMAKE_OSX_ARCHITECTURES`](https://cmake.org/cmake/help/v3.14/variable/CMAKE_OSX_ARCHITECTURES.html) to `"arm64;x86_64"`
- set [`CMAKE_IOS_INSTALL_COMBINED`](https://cmake.org/cmake/help/v3.14/variable/CMAKE_IOS_INSTALL_COMBINED.html) to `1`

Just like here, XCode needs to be the generator if doing device and simulator.

Not sure that the native support handles everything that @leetal's toolchain did, but it might be worth giving it a shot.

**Comment by leetal** [comment] 2019-08-13 11:53
**Using Xcode 10.3 and CMake 3.14.5**

From the example-lib folder:
Running `cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS64COMBINED` followed by `cmake --build . --config Release --target install` will install a static binanary (libexample.a) with both x86_64 and arm64 into the example-app/example-lib/lib folder.

**Comment by farfromrefug** [comment] 2019-08-22 14:43
@leetal  i am facing that issue too. I am wondering if it is not because libs for simulator/iphoneos are built in the same dir. For the project i am building (vxl) the libraries are generated inside the build/lib/Debug. There is no notion of Simulator or iphoneos. Consequently it would get overwritten preventing lipo to merge it. I might not understand how it is built though.

**Comment by ShengHuaWu** [comment] 2019-09-06 10:08
@nae986 @jonmcclung @farfromrefug
I encountered the same issue this week, but it has been solved by placing `install(TARGETS my_lib DESTINATION lib)` inside a proper `CMakeLists.txt` file. 

Here is my project structure:
```
my_project
│   CMakeLists.txt 
│   ...
|
└───my_lib
│   │   CMakeLists.txt <--- place `install(TARGETS my_lib DESTINATION lib)` here.
│   │   ...
│   
└───my_other_exe
    │   CMakeList.txts
    │  ...
```

As a result, `cmake --build . --config Debug --target install` can produce `libmy_lib.a` for `arm64` and `x86_64` in the `Debug-iphoneos` and `Debug-iphonesimulator` folders respectively. Then, I create the fat library with `lipo --create`.
Hopefully, this can give some clues for solving your problems. 🙂

**Comment by leetal** [comment] 2019-09-09 06:51
I wonder if i shall report this upstreams or fix this myself in the toolchain.. Because after testing this, it does indeed look like what @ShengHuaWu is saying is correct. The install target must be placed on the correct level in the CMake hierarchy.

**Comment by wudijimao** [comment] 2019-09-18 14:24
Thanks for @ShengHuaWu , but still have to do with `lipo --create manully. `
Let's check it out!!

**Comment by xxseabxx** [comment] 2019-12-12 09:57
First of all the COMBINED feature is very nice.
Tried also to build FAT Library for arm64,armv7,armv7s with the new feature. I'd like to avoid lipo too. By command looks as following
`ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DENABLE_BITCODE=TRUE -DENABLE_ARC=FALSE -DARCHS="arm64,armv7,armv7s`

My questions:
-  do ARCHS support more architecture ?
- do ARCHS totally overwrite the OS64COMBINED architectures?
- could I build 64 and armv7 together with the current state without lipo ?

**Comment by russes** [comment] 2020-01-08 22:53
If you integrate this iOS.cmake into an existing project & attempt to build using OS64COMBINED, you may see this error when the libraries are being generated:

`CMake Error at /opt/local/share/cmake-3.16/Modules/CMakeIOSInstallCombined.cmake:213 (message): destination is not absolute: install/lib/libofstd.a`

`Call Stack (most recent call first):`

 ` ofstd/libsrc/cmake_install.cmake:49 (ios_install_combined)`
 ` ofstd/cmake_install.cmake:37 (include)`
 ` cmake_install.cmake:96 (include)`

If you build using the SIMULATOR64 option, there's no problem.

If I look at the existing project, it looks as if libraries are generated through this CMake built-in:

`target_link_libraries(${TARGET} ${ARGN})`

---

One more thing:  I created a similar iOS.cmake a couple of years ago.  Getting this to work is painful.  I have a lot of sympathy for the author.

**Comment by russes** [comment] 2020-02-21 15:37
When you build with OS64COMBINED, you must ensure all library archives are referenced by a fully-resolved pathname to the archive.

`set (CMAKE_INSTALL_PREFIX "install")
set (CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install")`

Look at the two lines above.  The first line causes my OS64COMBINED builds to fail, because my library archives are referenced using a relative pathname.  Changing my install prefix to the second line of code causes my OS64COMBINED builds to mostly complete.

When you are attempting to debug OS64COMBINED build issues, start with the CMake module named CMakeIOSInstallCombined.cmake.

Note:  This change does not fix the "lipo -remove" error many of you are seeing.

**Comment by leetal** [comment] 2022-01-08 06:21
Most of the issues mentioned here have been solved upstream in CMake and the important things are mentioned in the README. Just remember to first run with "cmake --build ..." followed by "cmake --install ..." on a recent version (above 3.21.0) of CMake. Closing this since the original issue was actually caused by a bug in CMake.

**Closed by leetal** 2022-01-08 06:21 UTC
